[workspace]
authors = ["shi_jie <1592277253@qq.com>"]
channels = ["astra-toolbox", "conda-forge"]
name = "sparse_view_dataset"
platforms = ["linux-64"]
version = "0.1.0"


[system-requirements]
cuda = "12.0"

[pypi-options]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"



[dependencies]
pytorch-gpu = "==2.8.0"
tqdm = ">=4.67.1,<5"
nibabel = ">=5.3.2,<6"
imageio = ">=2.37.0,<3"
pytest = "*"
scikit-image = ">=0.25.2,<0.26"
typer = ">=0.20.0,<0.21"
pytorch3d = ">=0.7.7,<0.8"
odl = ">=0.8.3,<0.9"
astra-toolbox = ">=2.4.0,<3"


[pypi-dependencies]
sparse_view_dataset = { path = ".", editable = true }
pyvista = { version = ">=0.46.3, <0.47", extras = ["all"] }

