[workspace]
authors = ["shi_jie <1592277253@qq.com>"]
channels = ["astra-toolbox", "conda-forge"]
name = "sparse_view_dataset"
platforms = [{ platform = "linux-64", cuda = "12" }]
version = "0.1.0"


[pypi-options]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

[tasks]
crop = "python main.py crop"
project = "python main.py project"
project-once = "python main.py project-once"

[dependencies]
pytorch-gpu = "==2.8.0"
tqdm = ">=4.67.1,<5"
nibabel = ">=5.3.2,<6"
imageio = ">=2.37.0,<3"
pytest = "*"
scikit-image = ">=0.25.2,<0.26"
pytorch3d = ">=0.7.7,<0.8"
odl = ">=0.8.3,<0.9"
astra-toolbox = ">=2.4.0,<3"
notebook = ">=7.5.6,<8"
cyclopts = ">=4.22.0,<5"
pydicom = ">=3.0.2,<4"


[pypi-dependencies]
sparse_view_dataset = { path = ".", editable = true }
pyvista = { version = ">=0.46.3, <0.47", extras = ["all"] }
diffdrr = ">=0.6.1, <0.7"

