---
defaults:
  - wandb: null
  - cam_embd: null
  - _self_
general:
  device: 0
  random_seed: 0
data:
  training_resolution: 128
  fov: 51.98948897809546
  subset: -1
  input_images: 1
  origin_distances: false
  num_projs: 16
  center_mask_threshold: 0.2
opt:
  iterations: 500001
  base_lr: 0.00001
  batch_size: 1
  betas:
    - 0.9
    - 0.999
  loss: l2
  imgs_per_obj: 4
  ema: 
    use: true
    update_every: 100
    update_after_step: 100
    beta: 0.9999
  lambda_lpips: 0.01
  start_lpips_after: 300001
  pretrained_ckpt: null
  step_lr_at: 300001

model:
  max_sh_degree: 1
  inverted_x: false
  inverted_y: true
  name: SingleUNet
  out_channels: 64
  opacity_scale: 1.0
  opacity_bias: -2.0
  scale_bias: 0.02
  scale_scale: 0.003
  intensity_scale: 1.0
  intensity_bias: 0.0
  sigma_scale: 0.1
  sigma_bias: 0.00001
  xyz_scale: 0.1
  xyz_bias: 0.0
  depth_scale: 1.0
  depth_bias: 0.0
  network_without_offset: false
  network_with_offset: true
  attention_resolutions:
  - 16
  num_blocks: 4
  cross_view_attention: false
  base_dim: 128
  isotropic: False

logging:
  ckpt_iterations: 1000
  val_log: 1000
  loss_log: 1000
  loop_log: 1000
  render_log: 1000

Gaussians_Model:
  sh_degree: 3
  _source_path: ""
  _model_path: ""
  _images: "images"
  _resolution: -1
  _white_background: False
  data_device: "cuda"
  eval: False
Gaussians_Opt:
  iterations: 8000
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30_000

  density_lr: 0.01

  sigma_lr: 0.01

  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15_000
  densify_grad_threshold: 0.0002
  random_background: False

output:
  name: splatter

comparison:
  # dataset: "CAS"
  # num_proj: 16
  # gaussian_predictor_pretrained_model: "CA_pcd_cas_far_sample_260000.pth"
  # num_init_gaussian: 8000
  # max_iter: 8000
  # save_dir: "/data/xuemingfu/NeRP/gaussian_splatter_result_camera"
  # pretrain_model_path: "/data/xuemingfu/NeRP/gaussian_splatter_pretrain_model_new_camera"
    # dataset: "CCTA"
    # num_proj: 16
    # gaussian_predictor_pretrained_model: "paper_modelv13++.pth"
    # num_init_gaussian: 8000
    # max_iter: 8000
    # save_dir: "/media/I/xcw/3DGR-CAR-main/3dgs-car/gaussian_gcp_result_16view_time_test"
    # pretrain_model_path: "/media/I/xcw/3DGR-CAR-main/ckpt_oral"
    dataset: "CAS"
    num_proj: 16
    # gaussian_predictor_pretrained_model: "paper_modelv13++.pth"
    gaussian_predictor_pretrained_model: "paper_modelv13++.pth"
    num_init_gaussian: 4000
    max_iter: 8000
    save_dir: "/media/I/xcw/3DGR-CAR-main/3dgs-car/gaussian_gcp_result_16view"
    # pretrain_model_path: "/media/I/xcw/3DGR-CAR-main/ckpt_oral"
    pretrain_model_path: "/media/I/xcw/3DGR-CAR-main/ckpt_oral"

comparison_cas:
  dataset: "CAS"
  num_proj: 2
  gaussian_predictor_pretrained_model: "paper_modelv13++_cas.pth"
  num_init_gaussian: 8000
  max_iter: 8000
  save_dir: "/data/xuemingfu/NeRP/gaussian_splatter_result_new"
  pretrain_model_path: "/data/xuemingfu/NeRP/gaussian_splatter3_pretrain_model_new"

comparison_bk:
  dataset: "CCTA"
  num_proj: 2
  gaussian_predictor_pretrained_model: "paper_modelv14++294000F.pth"
  num_init_gaussian: 8000
  max_iter: 8000
  save_dir: "/data/xuemingfu/NeRP/gaussian_splatter_result"
  pretrain_model_path: "/data/xuemingfu/NeRP/gaussian_splatter3_pretrain_model"

cam_embd:
  embedding: null